Added two tests
algorithms-club/algorithms-dmytrenko pull request #1
Opened 2017-03-31 12:59 UTC by AlexDoh

Added two tests from codefroces

2017-04-05 21:05 UTC, pavlom0x requested changes
Description very general
you should describe in pull request what functionality you added
mention what it should solve/do

### Example

Added methods for solving tasks
- watermelon
- nextYearFind
- tests for methods

2017-04-05 21:05 UTC, pavlom0x commented on entry-test/coverByDominoes.js
> +};
I think you should read task description again.
You should have three input value *boardHeight*, *boardWidth* and *DominoseHeight*

2017-04-05 21:05 UTC, PavelMelnyk commented on entry-test/nextRound.js
> +function nextRound(allParticipants, lowestPlaceForNextRound, arr){
I can't understand what the task it is
provide me with a link for description

2017-04-08 05:27 UTC, AlexDoh commented on entry-test/coverByDominoes.js
> +};
http://codeforces.com/problemset/problem/50/A

Size of dominoes are standart - 2x1

2017-04-08 05:28 UTC, AlexDoh commented on entry-test/nextRound.js
> +function nextRound(allParticipants, lowestPlaceForNextRound, arr){
http://codeforces.com/problemset/problem/158/A

2017-04-28 22:22 UTC, merged