problem with unionFind test, it returns all elements from array as "true", when expected digits
algorithms-club/algorithms-dmytrenko pull request #2
Opened 2017-04-08 09:49 UTC by AlexDoh

problem with unionFind test, it returns all elements from array as "true", when expected digits

2017-04-17 21:37 UTC, pavlom0x requested changes

2017-04-17 21:37 UTC, PavelMelnyk commented on entry-test/unionFind.js
> +            if(this._elements[i] = this._elements.indexOf(i)){
are you sure?  `=` 
if you want to compare values, use `==` or `===`

2017-04-17 21:37 UTC, PavelMelnyk commented on entry-test/unionFind.js
> +            if(this._elements[i] = this._elements.indexOf(i)){
each time you call indexOf, it go through all array

please tell me what complexity(in Big O notation) of this method?

2017-04-21 21:27 UTC, AlexDoh commented on entry-test/unionFind.js
> +            if(this._elements[i] = this._elements.indexOf(i)){
if it goes through all array - it is O(n).

2017-04-21 21:27 UTC, AlexDoh commented on entry-test/unionFind.js
> +            if(this._elements[i] = this._elements.indexOf(i)){
But I still don't understand why the array has only 'true' values...

2017-04-22 05:21 UTC, closed without merging