Added Selection sort, Insertion sort and Shell sort algorithms
algorithms-club/algorithms-dmytrenko pull request #8
Opened 2017-05-05 23:04 UTC by AlexDoh

Added Selection sort, Insertion sort and Shell sort algorithms.

All of them use compareNumbers function, which return min value.

2017-05-06 14:31 UTC, YuriiHoliuk requested changes
Selection і Insertion - все ок, код гуд
Shell - вісутній, треба переписати
не реалізовані shuffle та isSorted - з ними можна ранити тести на рандомних масивах довільної довжини, а так тести трохи не серйозні, не факт, що тестована просто функція не повертає прописаний в тесті масив

2017-05-06 14:31 UTC, YuriiHoliuk commented on entry-test/selectionSort.js
> +    if(collection.length === 0){
тут вже напевне поспішав, пробіли вже закінчились)

2017-05-06 14:31 UTC, YuriiHoliuk commented on entry-test/shellSort.js
> +        for (let j = 0; j + i - 1 < collection.length; j++) {
-1 тут не потрібен і тільки заважає читати код

2017-05-06 14:31 UTC, YuriiHoliuk commented on entry-test/shellSort.js
> +};
**Це не shell sort**
по перше, тому, що при знаходженні елементу, який треба переставити, після перестановки потрібно далі перевіряти чи не менший він за наступний елемент через інтервал, це доведе його якомога ближче до кінцевої позиції,
така фіча в основному потребує третього циклу
в тебе елемент переставляється 1 раз і все

верхній цикл, це інтервали, як я зрозумів, вони можуть вибиратись по різному, але не зменшенням на 1, це важливо, в інтервалах вся суть цього алгоритму

ну і по перформансу видно, що це не шелл сорт, він сортує приблизно як selection

2017-05-07 11:00 UTC, AlexDoh commented on entry-test/selectionSort.js
> +    if(collection.length === 0){
:)

2017-05-07 11:04 UTC, AlexDoh commented on entry-test/shellSort.js
> +};
Да, ты прав, я залью shell. Это кстати метод сортировки - comb Sort (сортировка расчёской). https://en.wikipedia.org/wiki/Comb_sort . На нём был основал shell :) Оставлю уже его, а shell добавлю отдельно.

2017-05-07 11:11 UTC, AlexDoh commented
Переименовал shellSort.js в comb сортировку. Добавил isSorted, shuffle & shell, и включил их в тесты.

2017-05-07 12:19 UTC, YuriiHoliuk approved these changes
Молодець, все виправив!)

2017-05-12 11:59 UTC, tatsiak approved these changes
по коду - ОК
Разве что пробелы в файлах spec лишние.
В остальном approve.

2017-05-17 09:39 UTC, merged